name: Build project web client output and publish to github pages.

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust & Cargo dependencies environment
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build project
        run: trunk build --release
      - name: Deploy to Github pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh_pages
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}